---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: udaconnect-location-api
  name: udaconnect-location-api
spec:
  ports:
  - name: 5000-30003
    port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30003  # Updated NodePort
  selector:
    app: udaconnect-location-api
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: udaconnect-location-api
  name: udaconnect-location-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udaconnect-location-api
  template:
    metadata:
      labels:
        app: udaconnect-location-api
    spec:
      containers:
      - image: ezachs/location-service:latest  # Use the appropriate image name for the Location service
        name: udaconnect-location-api
        imagePullPolicy: Always
        env:
        - name: DB_USERNAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: DB_PASSWORD
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_NAME
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: db-env
              key: DB_PORT
      restartPolicy: Always

